Update configure
Create separate step to verify proxmox connection since ./configure --verify needs SSH connection to ansible hosts by default

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -17,11 +17,13 @@ cat << EOF
 Usage: $(basename "$0") <options>
     -h, --help                      Display help
     --verify                        Verify .config.env settings
+    --verify-proxmox                Verify .config.env settings for proxmox
 EOF
 }
 
 main() {
     local verify=
+    local verify_proxmox=
 
     parse_command_line "$@"
 
@@ -35,8 +37,10 @@ main() {
         verify_age
         verify_git_repository
         verify_cloudflare
-        verify_proxmox_hosts
         verify_success
+    elif [[ "${verify_proxmox}" == 1 ]]; then
+    	verify_proxmox_hosts   
+	verify_proxmox_vms
     else
         # generate sops configuration file
         envsubst < "${PROJECT_DIR}/tmpl/.sops.yaml" \
@@ -69,12 +73,14 @@ main() {
             > "${PROJECT_DIR}/provision/terraform/cloudflare/secret.sops.yaml"
         # encrypt terraform secrets
         sops --encrypt --in-place "${PROJECT_DIR}/provision/terraform/cloudflare/secret.sops.yaml"
-         # generate proxmox secrets
-        envsubst < "${PROJECT_DIR}/tmpl/terraform/proxmox/secret.sops.yaml" \
-            > "${PROJECT_DIR}/provision/terraform/proxmox/secret.sops.yaml"
-        # encrypt proxmox secrets
-        sops --encrypt --in-place "${PROJECT_DIR}/provision/terraform/proxmox/secret.sops.yaml"
-        # generate ansible settings
+	if [[ "${BOOTSTRAP_PROXMOX_ENABLED}" == "true" ]]; then
+            # generate proxmox secrets
+            envsubst < "${PROJECT_DIR}/tmpl/terraform/proxmox/secret.sops.yaml" \
+                > "${PROJECT_DIR}/provision/terraform/proxmox/secret.sops.yaml"
+            # encrypt proxmox secrets
+            sops --encrypt --in-place "${PROJECT_DIR}/provision/terraform/proxmox/secret.sops.yaml"
+        fi
+	# generate ansible settings
         envsubst < "${PROJECT_DIR}/tmpl/ansible/kube-vip.yml" \
             > "${PROJECT_DIR}/provision/ansible/inventory/group_vars/kubernetes/kube-vip.yml"
         # include kube-vip if enabled
@@ -107,6 +113,9 @@ parse_command_line() {
             --verify)
                 verify=1
                 ;;
+	    --verify-proxmox)
+                verify_proxmox=1
+                ;;
             *)
                 break
                 ;;
@@ -117,6 +126,9 @@ parse_command_line() {
 
     if [[ -z "$verify" ]]; then
         verify=0
+    fi
+    if [[ -z "$verify_proxmox" ]]; then
+        verify_proxmox=0
     fi
 }
 
@@ -349,37 +361,41 @@ verify_cloudflare() {
 verify_promox_hosts() {
     # is this needed?
 	# local node_id=
-	local node_name=
-	local api_url=
-	local api_id=
-	local api_secret=
-    local errors=
+	local api_url="BOOSTRAP_PROXMOX_API_URL"
+	local api_id="BOOSTRAP_PROXMOX_API_ID"
+	local api_secret="BOOSTRAP_PROXMOX_API_SECRET"
+    	local errors=
+	_has_envar "${api_url}"
+	_has_envar "${api_id}"
+	_has_envar "${api_secret}"
 
-    # Reads names from BOOTSRTAP_PROXMOX_NODE_NAMES=foo,bar
+    	# Reads names from BOOTSRTAP_PROXMOX_NODE_NAMES=foo,bar
 	for node_name in ${BOOTSRTAP_PROXMOX_NODE_NAMES//,/}; do
 		# is this needed?
-        # node_id=$(echo "${var}" | awk -F"_" '{print$5}')
-		api_url="BOOSTRAP_PROXMOX_API_URL"
-		api_id="BOOSTRAP_PROXMOX_API_ID"
-		api_secret="BOOSTRAP_PROXMOX_API_SECRET"
+        	# node_id=$(echo "${var}" | awk -F"_" '{print$5}')
 		# _has_envar "${node_id}"
 		_has_envar "${node_name}"
-		_has_envar "${api_url}"
-		_has_envar "${api_id}"
-		_has_envar "${api_secret}"
 
 		# Test proxmox auth credentials
 		# curl  --insecure --cookie "$(<cookie)" https://$APINODE:8006/api2/json/nodes/$TARGETNODE/status | jq '.'
-    	proxmox_api_connection=$(curl  --insecure --cookie "$(<cookie)" https://$api_url/api2/json/nodes/$node_name/status)
+    		proxmox_api_connection=$(curl  --insecure --cookie "$(<cookie)" https://$api_url/api2/json/nodes/$node_name/status \
+			-H "Authorization: PVEAPIToken=${api_id}=${api_secret}"		
+		)
 		
 		if [[ "$(echo "${proxmox_api_connection}" | jq ".")" == "true" ]]; then
 			_log "INFO" "Connection to proxmox nodes OK"
 		else
-            errors=$(echo "${proxmox_api_connection}" | jq -c ".errors")
-		    _log "ERROR" "Unable to connect to ${node_name}: ${errors}"
-		    exit 1
+            		errors=$(echo "${proxmox_api_connection}" | jq -c ".errors")
+		   	_log "ERROR" "Unable to connect to ${node_name}: ${errors}"
+		    	exit 1
 		fi
 	done	
+}
+
+verify_promox_vms() {
+	local vm_="BOOSTRAP_PROXMOX_VM_"
+    	local errors=
+	_has_envar "${vm_}"
 }
 
 verify_ansible_hosts() {
@@ -428,8 +444,12 @@ verify_ansible_hosts() {
         if ssh -q -o BatchMode=yes -o ConnectTimeout=5 "${!node_username}"@"${!var}" "true"; then
             _log "INFO" "SSH into host '${!var}' with username '${!node_username}' was successfull"
         else
-            _log "ERROR" "SSH into host '${!var}' with username '${!node_username}'was NOT successful, did you copy over your SSH key?"
-            exit 1
+	    if [[ "${BOOTSTRAP_PROXMOX_ENABLED}" == "true" ]]; then
+            	_log "ERROR" "SSH into host '${!var}' with username '${!node_username}'was NOT successful, has VMs been created in proxmox? See 'task proxmox:' and 'task verify-proxmox'"
+	    else
+	    	_log "ERROR" "SSH into host '${!var}' with username '${!node_username}'was NOT successful, did you copy over your SSH key?"
+	    fi
+	    exit 1
         fi
     done
 }
